services:
  time-table:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bridge
    restart: always

networks:
  bridge:
    driver: bridge
